{% set name = "CBFlib" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/dials/cbflib/archive/refs/tags/CBFlib-{{ version }}.tar.gz
    folder: cbflib
    sha256: 81d8ea4b75ba2cab7f94a6b20a32b8ca099405a073201776c64064b64c7a4d30
    patches:
      - 04-fgetln.patch
      - 05-mkstemplate.patch
      - 06-realpath.patch
      - 07-vla.patch
      - 08-libtiff-public-api.patch
      - 09-pycbf-dials.patch
      - 10-cmake.patch
      - 11-cmakelist.patch
      - 12-msvc.patch
      - 13-warnings.patch
      - 14-conda-forge.patch
  - url: http://downloads.sf.net/cbflib/CBFlib_{{ version }}_Data_Files_Input.tar.gz
    sha256: a13d6f740a12dd7380e451ce4107c0f07abd2d6795c9cb261ac5bb5f50fa680b
    folder: data-input
    patches:
      - cbflib-data-input-{{ version }}.patch
  - url: http://downloads.sf.net/cbflib/CBFlib_{{ version }}_Data_Files_Output.tar.gz
    sha256: 565338960af638263a26525f43f3d791a75a8bf55599f12809547f66830b913f
    folder: data-output
    patches:
      - cbflib-data-output-{{ version }}.patch

build:
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}      # [win]
    - libtiff
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake      >=3.18
    - make               # [unix]
    - pkg-config         # [win]
  host:
    - cqrlib
    - hdf5       >=1.10
    - libtiff    >=4.4
    - pcre2              # [win]
  run:
    - hdf5
    - pcre2              # [win]

test:
  commands:
    - test -d "${PREFIX}/include/cbflib"            # [unix]
    - if not exist "%LIBRARY_INC%\cbflib\\" exit 1  # [win]

about:
  home: https://github.com/yayahjb/cbflib
  summary: 'Functions to read and write CBF and imgCIF data files'
  description: |
    CBFlib is a library of ANSI C functions providing a simple
    mechanism for accessing Crystallographic Binary Files (CBF) and
    image-supporting CIF (imgCIF) files.
  license: LGPL-2.0-or-later
  license_file:
    - cbflib/doc/gpl.txt
    - cbflib/doc/lgpl.txt
  dev_url: https://github.com/yayahjb/cbflib

extra:
  recipe-maintainers:
    - hattne
